find_path(EPICS_INCLUDE_DIR NAMES epicsVersion.h PATHS ${CONAN_INCLUDE_DIRS_EPICS})
find_path(EPICS_INCLUDE_OS_DIR NAMES osdEvent.h PATHS ${EPICS_INCLUDE_DIR}/os/Linux ${EPICS_INCLUDE_DIR}/os/Darwin)
find_path(EPICS_INCLUDE_COMP_DIR NAMES compilerSpecific.h PATHS ${EPICS_INCLUDE_DIR}/compiler/gcc ${EPICS_INCLUDE_DIR}/compiler/clang)

set(EPICS_INCLUDE_DIR ${EPICS_INCLUDE_DIR} ${EPICS_INCLUDE_OS_DIR} ${EPICS_INCLUDE_COMP_DIR})

find_library(EPICS_LIBRARY NAMES ${CONAN_LIBS_EPICS} PATHS ${CONAN_LIB_DIRS_EPICS})

set(EPICS_FOUND TRUE)  
set(EPICS_LIBRARIES ${EPICS_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(EPICS DEFAULT_MSG
    EPICS_INCLUDE_DIR
    EPICS_LIBRARIES
    EPICS_LIBRARY
)